### ISSUE TITLE
Organiseren van een vaste (niet openbare) plaats voor opslag van niet-openbare / interne documenten rondom Proeftuin ZGW in afstemming met scrumteam

### ISSUE THREAD

**Issue by Tim-Hartog** [GemeenteUtrecht/ZGW#104]
# Scrumtaak

[beschrijf de scrumtaak]

[assign aan teamlid]

**Comment by frankmijn** [comment]
@Tim-Hartog wat is deze locatie geworden?

**Comment by Tim-Hartog** [comment]
Nog niets... We hebben en verwachten niet veel gesloten documenten en stellen het regelen van een plek voor nu nog even uit.... Wellicht later als de behoefte opnieuw een concreet ontstaat.

**Comment by frankmijn** [comment]
aah, ik had een BPMN-bestand dat ik wil delen, is ook niet geheim. Zal het op slack zetten.
