### ISSUE TITLE
Als teamlid wil ik binnen een zaaktype per status een doorlooptijd in kunnen richten. 

### ISSUE THREAD

**Issue by JurjenBert** [GemeenteUtrecht/ZGW#115]
...zodat de voortgang van de zaak per statusovergang kan volgen.

**Bepaling prioriteit door PO**

- [ ] TODO

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] TODO

**Acceptatiecriteria**
- [ ] TODO

**Taken**
- [ ] TODO

**Comment by sergei-maertens** [comment]
Dit veld moet nog in de ZTC API ontsloten worden, moet aangedragen worden in vng-Realisatie/gemma-zaken
