### ISSUE TITLE
Als developer wil ik een zaak koppelen aan document in Alfresco.

### ISSUE THREAD

**Issue by JostCrow** [GemeenteUtrecht/ZGW#128]
...zodat [vul aan].

**Bepaling prioriteit door PO**

- [ ] TODO

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] TODO

**Acceptatiecriteria**
- [ ] TODO

**Taken**
- [ ] TODO

**Comment by CMasselink** [comment]
Om deze reden wil ik eigenlijk de richting van de relatie omdraaien waarbij de relatie tussen een zaak en een informatieobject in het ZRC gelegd wordt. Al kan je dan wellicht nog steeds in de knoop raken met je metadata. 
Hanteer je de Alfresco/cmis structuur zoals die gespecificeerd wordt in de zaak-documentservices 1.2?

**Comment by JostCrow** [comment]
Ik heb dezelfde structuur als die bij Haarlem werd gebruikt. Volgens mij is dat inderdaad op zaak-documentservices 1.2 gebaseerd.

**Comment by JostCrow** [comment]
De 2 problemen die ik hierboven opnoem hebben te maken met cmis/alfresco zelf.

Het eerste plan was om de documenten in de zaakfolder te plaatsen waar het bijhoort. Alleen je kan voor een bestand niet meerdere locaties mee geven (wat logisch is). Daar ging de oplossing over. Gaan we bestanden dus symlinken naar de juiste zaakfolder of gaan we de documenten in alfresco zelf niet in een zaakfolder plaatsen.
