### ISSUE TITLE
Als ontwikkelaar wil ik dat persoonsgegevens uit de BRP opgehaald worden...

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/ZGW#13]
...zodat aan het Common Ground principe voldaan wordt.

Betrokkenen bij de zaak, en zaakobjecten als huwelijkspartners, getuigen, kinderen e.d. worden niet in het ZRC opgeslagen, maar deze informatie leeft idealiter in een BRP.

Dit kan nog niet gebouwd worden omdat een dergelijke omgeving niet bestaat/ingericht is.

**Bepaling prioriteit door PO**

- [ ] TODO

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] TODO

**Acceptatiecriteria**
- [ ] TODO

**Taken**
- [ ] TODO

**Comment by CMasselink** [comment]
@sergei-maertens voor de huwelijksplanner heeft Bart op verzoek de NLX BRP mock api aangepast.
https://gitlab.com/commonground/nlx-demo/tree/master/brp-mock-service
Wat nu kan: op basis van BSN een persoon opzoeken waarna je die als object/resource terug krijgt. 
+ je kan een verwijzing naar de resource opnemen.
Voor testdoeleinden wel goed bruikbaar. 
Datamodel is niet helemaal RSGB compliant maar het is een begin.
