### ISSUE TITLE
Als medewerker / manager / burger wil ik een overkoepelende huwelijkszaak (waarbinnen de twee bestaande huwelijkszaken vallen) zodat...

### ISSUE THREAD

**Issue by Tim-Hartog** [GemeenteUtrecht/ZGW#149]
ik eenvoudig overzicht welke deelzaken bij welk huwelijk behoren.

Generieke functie: Doel is om de burger duidelijkheid te verschaffen over één event, dat mogelijk voor ons uit meerdere zaken bestaat. Communicatie verloopt via één zaak-/identificatienummer. Hiervoor kan gebruik worden gemaakt van een regiezaak, maar dit is ook op te lossen door een dossier te creëren wat feitelijk alleen een inzagefunctie is die alle zaken bij elkaar toont als één event. 

**Bepaling prioriteit door PO**

- [ ] TODO

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] TODO

**Acceptatiecriteria**
- [ ] TODO

**Taken**
- [ ] TODO

**Comment by CMasselink** [comment]
Lijkt me goed om dit soort user storys, die in dit geval gaan over zaaktype ontwerp, samen met burgerzaken uit te werken.

**Comment by MichelleDautzenberg** [comment]
Ik sluit deze omdat we deze toch niet kan oppakken.
