### ISSUE TITLE
Als medewerker wil ik dat er een overkoepeld huwelijksdossier wordt aangemaakt, wanneer daarbinnen een losse huwelijkszaak wordt aangemaakt

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#155]
zodat... de klant direct het huwelijksdossier nummer kan ontvangen en straks al hun lopende huwelijkszaken kan inzien vanuit één dossier.

Aanmaak van dossier ongeachte welke deelzaak als eerste wordt opgestart. 

**Bepaling prioriteit door PO**

- [ ] TODO

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] TODO

**Acceptatiecriteria**
- [ ] TODO

**Taken**
- [ ] TODO

**Comment by Tim-Hartog** [comment]
**In afstemming met productowner:**
Huwelijksplanner wordt niet uitontwikkeld. ZAC laat reeds voldoende mogelijkheden zien om zaken vanuit verschillende perspectieven te bekijken. Alleen het geo-perspectief vergt naar zijn behoefte nog verdere uitwerking, welke we binnen BING verder oppakken.
