### ISSUE TITLE
AFGEVOERD: Als medewerker wil ik dat alle communicatie over een huwelijk plaatsvindt adhv een huwelijksdossier nummer

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#156]
zodat de klant geen last heeft van communicatie op basis van verschillende zaaknummers 

Voor de ZAC betekent dit dat het invoeren van hoofdzaaknummer ervoor zorgt dat het hele dossier getoond wordt.

**Bepaling prioriteit door PO**

- [ ] TODO

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] TODO

**Acceptatiecriteria**
- [ ] TODO

**Taken**
- [ ] TODO

**Comment by Tim-Hartog** [comment]
**In afstemming met productowner:**
Huwelijksplanner wordt niet uitontwikkeld. ZAC laat reeds voldoende mogelijkheden zien om zaken vanuit verschillende perspectieven te bekijken. Alleen het geo-perspectief vergt naar zijn behoefte nog verdere uitwerking, welke we binnen BING verder oppakken.
