### ISSUE TITLE
ADFGEVOERD: Als medewerker wil ik in een huwelijksdossier kunnen zien wat de status en het resultaat is van de zaken waar een dossier uit bestaat

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#158]
zodat... ik één totaaloverzicht heb van alles wat we nog geregeld moet worden voor een huwelijk 

**Bepaling prioriteit door PO**

- [ ] TODO

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] TODO

**Acceptatiecriteria**
- [ ] TODO

**Taken**
- [ ] TODO

**Comment by Tim-Hartog** [comment]
**In afstemming met productowner:**
Huwelijksplanner wordt niet uitontwikkeld. ZAC laat reeds voldoende mogelijkheden zien om zaken vanuit verschillende perspectieven te bekijken. Alleen het geo-perspectief vergt naar zijn behoefte nog verdere uitwerking, welke we binnen BING verder oppakken.
