### ISSUE TITLE
AFGEVOERD: Als medewerker wil ik dat het huwelijksdossier verwijzingen naar onderliggende zaken bevat (melding voorgenomen huwelijk, aanvraag huwelijk behandelen, Babs voor een dag)

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#160]
zodat... informatie opgeslagen blijft bij de specifieke zaken (en daarmee dubbele opslag en autorisatieproblemen voorkomen worden), maar ik wel overzicht heb over het gehele huwelijksdossier.

Vanuit het overzicht wil ik de zaken af kunnen handelen die ik volgens mijn  autorisatie af mag handelen.

**Bepaling prioriteit door PO**

- [ ] TODO

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] TODO

**Acceptatiecriteria**
- [ ] TODO

**Taken**
- [ ] TODO

**Comment by Tim-Hartog** [comment]
**In afstemming met productowner:**
Huwelijksplanner wordt niet uitontwikkeld. ZAC laat reeds voldoende mogelijkheden zien om zaken vanuit verschillende perspectieven te bekijken. Alleen het geo-perspectief vergt naar zijn behoefte nog verdere uitwerking, welke we binnen BING verder oppakken.
