### ISSUE TITLE
Als functioneel beheerder wil ik een KetenInzageComponent (KIC) kunnen configureren

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#162]
...waardoor ik alle zaken van een burger (gebundeld) aan de burger kan tonen.

Dashboard/portaal waarop de burger kan inloggen om al zijn lopende en gesloten zaken in te zien. 
- Waarbij ik als FB kan configureren welke zaaktypen gezamenlijk als een dossier getoond moeten worden.
- eventueel integreren van taakapplicaties, zoals de huwelijksplanner? 

**Bepaling prioriteit door PO**

- [ ] TODO

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] TODO

**Acceptatiecriteria**
- [ ] TODO

**Taken**
- [ ] TODO

**Comment by Tim-Hartog** [comment]
**In afstemming met productowner:**
KIC wordt niet uitontwikkeld. BING-proces laat reeds voldoende mogelijkheden zien om zaken te relateren en vanuit verschillende perspectieven te bekijken. Alleen het geo-perspectief vergt naar zijn behoefte nog verdere uitwerking, welke we binnen BING verder oppakken.
