### ISSUE TITLE
[impediment] Als dev(ops) willen we dat er storage beschikbaar is voor Alfresco (en andere services)

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/ZGW#163]
...zodat we de Alfresco Helm chart succesvol kunnen deployen.

Per https://gitlab.com/gemeente-utrecht/zgw-kubernetes/merge_requests/1 hebben Jorik en ik een poging gedaan om Alfresco in de kubernetes cluster te deployen. Dit hangt momenteel op Persistent Volume Claims die in 'pending' state zijn omdat er geen Persistent Volumes beschikbaar zijn.

* we hebben geen rechten om Persistent Volumes in de cluster in te kijken/beheren/aanmaken
* we weten niet of er uberhaupt disk space is voor de PVs (Alfresco vraagt 20GB en 10GB)

We hebben ondersteuning nodig vanuit infrastructuur om dit ingericht te krijgen, eventueel met network storage oid. Het maakt ons niet veel uit hoe het eruit ziet, als we maar met PVCs aan de slag kunnen.

**Comment by Tim-Hartog** [comment]
14 mei 2019: Lazo Bozarov [07:05]
 Dag Tim, Contezza gaat as. Donderdag Alfresco installeren. Wel moet ik nog Bart van Delta 10 en Mike voor rechten Azure stack regelen. Ik hou je op de hoogte...
