### ISSUE TITLE
Als burger wil ik in mijn huwelijksdossier kunnen zien wat de status en het resultaat is van de zaken waar mijn dossier uit bestaat 

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#167]
...zodat ik overzicht heb over alles wat  ik voor mijn huwelijk moet regelen. 
Ik wil ook graag een verwachte doorlooptijd zien.
 
De ordening kan chrologisch zijn waarbij ik een aantal stappen en de voortgang daarbinnen kan zien. Een stap kan een mijlpaal binnen een zaak zijn, maar ook een deelzaak. Ook willen we binnen een stap zien of er nog documenten of informatie ontbreekt. Maw of ik actie kan/moet ondernemen.

De ordening kan ook parallel opgestarte zaken betreffen. 

**Bepaling prioriteit door PO**

- [ ] TODO

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] TODO

**Acceptatiecriteria**
- [ ] TODO

**Taken**
- [ ] TODO

**Comment by Tim-Hartog** [comment]
**In afstemming met productowner:**
Huwelijksplanner wordt niet uitontwikkeld. ZAC laat reeds voldoende mogelijkheden zien om zaken vanuit verschillende perspectieven te bekijken. Alleen het geo-perspectief vergt naar zijn behoefte nog verdere uitwerking, welke we binnen BING verder oppakken.
