### ISSUE TITLE
Als burger wil ik dat in mijn online dossier al mijn lopende en afgesloten zaken geclusterd naar onderwerp te raadplegen zijn

### ISSUE THREAD

**Issue by JurjenBert** [GemeenteUtrecht/ZGW#170]
...zodat ik goed zicht heb op de status van mijn overkoepelende dossiers.  
Ik wil dat mijn zaken worden geclusterd aan de hand van onderwerpen zoals een Huwelijk en een Verhuizing. Ik wil dan de voorgang op de zaken in hun onderlinge samenhang kunnen zien (in plaats van de voorgang van alle losse zaken). 
Er moet een onderscheid zijn tussen lopende en afgesloten dossier, zodat ik in mijn overzicht begin met wat er actueel is. 

**Bepaling prioriteit door PO**

- [ ] TODO

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] TODO

**Acceptatiecriteria**
- [ ] TODO

**Taken**
- [ ] TODO

**Comment by Tim-Hartog** [comment]
**In afstemming met productowner:**
KIC wordt niet uitontwikkeld. BING-proces laat reeds voldoende mogelijkheden zien om zaken te relateren en vanuit verschillende perspectieven te bekijken. Alleen het geo-perspectief vergt naar zijn behoefte nog verdere uitwerking, welke we binnen BING verder oppakken.
