### ISSUE TITLE
Als proeftuin teamlid wil ik Github en Slack kunnen benaderen vanuit mijn werkplek, zodat ik geen twee werkplekken tegelijk hoef te gebruiken

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#19]
Github en Slack ondersteunen de browsers van onze gemeentelijke werkplek niet, waardoor ik deze in de lokale omgeving op mijn laptop moet openen. Dat maakt het lastig om snel te schakelen of bijvoorbeeld teksten te copy-pasten

**Comment by CMasselink** [comment]
Tip: vraag Firefox aan en vervolgens bij FB de firefox versie die ze aan het testen zijn. Die heb ik nu ook beschikbaar en daar werkt Github en Slack goed mee:)
