### ISSUE TITLE
Als functioneel beheerder wil ik bij de inrichting van archiefgegevens van een zaaktype kunnen afwijken van de VNG selectielijst

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#203]
...zodat ik altijd kan afwijken van de selectielijst wanneer de situatie daarom vraagt en ik wettelijk die ruimte heb. Ik wil wel altijd kunnen zien van welk resultaattype uit de selectielijst het afwijkende resultaattype is afgeleid. 

**Bepaling prioriteit door PO**

- [ ] TODO

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] TODO

**Acceptatiecriteria**
- [ ] TODO

**Taken**
- [ ] TODO

**Comment by JurjenBert** [comment]
uitgezocht met Constantijn: wanneer je op zaaktypeniveau geen archiefactietermijn opgeeft, wordt de termijn uit de selectielijst gebruikt. Wanneer je ook nog een archiefactietermijn opgeeft, wordt die gebruikt. Hierdoor zou met de actietermijn je dus af kunnen wijken van de waarde in de selectielijst.
