### ISSUE TITLE
Als functioneel beheerder wil ik uitleg van Gemeente Haarlem over hun proces 'Afschrift Akte' en het gebouwde Camunda-proces hierbij

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#218]
...zodat ik deze input kan gebruiken bij het bouwen van een eigen proces in Camunda.

**Comment by Tim-Hartog** [comment]
Vervolgafstemming Lazo Bozarov:
Lazo gaat met Bas de Boer van Haarlem overleggen of proces daar draait en globale analyse wat er aan de hand kan zijn. We zijn er nog niet uit om de sourcecode los op te vragen en zelf op te pakken. Vraag was immers niet of we de code aan de praat zouden kunnen krijgen, maar of dergelijke ontwikkelingen eenvoudig herbruikbaar / uitwisselbaar / over te nemen zijn. Voor nu geen nadere actie totdat expliciet alsnog hiertoe opdracht aan proeftuin wordt gegeven.
