### ISSUE TITLE
BInG -> DRC: indicatie gebruiksrecht default niet False

### ISSUE THREAD

**Issue by JostCrow** [GemeenteUtrecht/ZGW#224]
Voor nu staat de indicatie_gebruiksrecht van een document standaard op False om een BInG zaak te kunnen sluiten.

Voor in de proeftuin is dit concept niet erg. Echter als dit naar productie gaat, zou dit problemen kunnen gaan opleveren met de rechten van de documenten.

**Comment by MichelleDautzenberg** [comment]
@sergei-maertens Kan deze gesloten? Of moet dit nog gebeuren?

**Comment by sergei-maertens** [comment]
Nee, maar komt wel ter vervallen als straks de CMIS integratie in Open Zaak klaar is (https://github.com/open-zaak/open-zaak/pull/540)

Ik houd hem open zodat we dit niet vergeten om er rekening mee te houden.
