### ISSUE TITLE
zorg voor document Mimetypes voor alfresco

### ISSUE THREAD

**Issue by JostCrow** [GemeenteUtrecht/ZGW#226]
Als er geen mimetype wordt mee gegeven aan alfresco kan deze niet geopend worden in alfresco zelf. 

Door een mimetype mee te geven zal het document beter tot zijn recht komen in alfresco

**Comment by MichelleDautzenberg** [comment]
@sergei-maertens Kan deze gesloten? Of moet dit nog gebeuren?
