### ISSUE TITLE
Als burger wil ik vóór of aan het begin van mijn melding/aanvraag weten welke stukken ik moet aanleveren

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#25]
...zodat ik deze kan verzamelen voordat ik met het formulier begin. 

Informerende tekst die aangeeft welke documenttypen relevant zijn voor uitgebreide/verkorte procedure. Zie ook #49

Noot: informatieobjecttypen uitlezen van (relevant) zaaktype

**Bepaling prioriteit door PO**

- [ ] TODO

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] TODO

**Acceptatiecriteria**
- [ ] TODO

**Taken**
- [ ] TODO

**Comment by sergei-maertens** [comment]
-> vooral inrichten ZTC
