### ISSUE TITLE
Custom variabele voor acties in Zaaksysteem

### ISSUE THREAD

**Issue by Frits-Ritense** [GemeenteUtrecht/ZGW#251]
In de Camunda Modeler willen we gebruik maken van een Custom proces variabele voor Zaakcreatie.

**Acceptance criteria**
Door een custom variabele in te zetten kan vanuit het model acties naar het systeem worden gedaan

**Comment by sergei-maertens** [comment]
@Frits-Ritense moet ik hier nog wat voor doen om dit correct mee te geven bij het starten van een process instance? In https://github.com/GemeenteUtrecht/process-platform zie ik geen documentatie o.i.d. waar ik op kan bouwen :)
