### ISSUE TITLE
Als aanvrager van een evenementenvergunning wil ik in één keer kunnen zien wat ik allemaal moet aanvragen en dit dan ook gelijk kunnen doen, 

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#270]
zodat ik niet achteraf verrast wordt met meer werk. 

We willen hier een simpel statisch formulier met een paar basic vragen.
Indien de vraag "Gaat u alcohol schenken?" wordt beantwoord met 'Ja' dan start er een evenementenvergunning zaak (Regiezaak) én een Ontheffing drank- en horecazaak. (bijdragezaak). 
Indien de vraag wordt beantwoord met 'Nee' start er alleen een evenementenvergunning zaak.

**Comment by sergei-maertens** [comment]
Aanvraagformulier:

* [ ] naam evenement
* [ ] start- en einddatum + tijd
* [ ] locatie (geo) - features (niet enkel 2D point)
* [ ] Contactpersoon gegevens (naam, telefoon + email)
* [ ] Alcohol schenken y/n?
