### ISSUE TITLE
Als aanvrager van een evenementenvergunning wil ik één zaaknummer en één contactpersoon voor alles rondom mijn evenement

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#271]
zodat mijn communicatie met de gemeente duidelijk en efficiënt is.  

De evenementenvergunning is de regiezaak, de ontheffing is een bijdragezaak. De communicatie verloopt altijd met het zaaknummer van de regiezaak. De casusregisseur is de vaste contactpersoon.

**Comment by sergei-maertens** [comment]
* 1 contactpersoon: zaakcoördinator
* 1 zaaknummer: van regiezaak (evenementvergunning regiezaak). Dus communicatie over horeca-aanvraag bijvoorbeeld, moet met het zaaknummer van de evenementenaanvraag.
