### ISSUE TITLE
Als aanvrager wil ik direct bij het invullen van mijn aanvraag zien of mijn evenement mogelijk is op de gekozen datum en locatie

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#273]
zodat ik niet onnodig werk verricht. 

Voor de demo gebruiken we hier één locatie voor met een reeds gepland evenement op die locatie (de markt).

**Comment by sergei-maertens** [comment]
Met start/einddatum/tijd parameters -> haal zaken op binnen Utrecht en beeld de geo-contouren af.
-> toon hover-tekst dat locatie niet beschikbaar is.

Op termijn: herhalende events op basis van 1x aanvraag doen (zoals een markt), nu out of scope.
