### ISSUE TITLE
Als casusregisseur wil ik inzage in alle evenementen waar ik regisseur van ben

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#276]
Voor de rol casusregisseur dient er inzage te komen op het niveau van een Evenement, hieronder vallen de zaaktypen Evenementvergunning (Regiezaak) en Ontheffing Drank- en Horeca (bijdragezaak). 

Zie ook wireframes van Jeroen.

**Comment by sergei-maertens** [comment]
Zie `1-main-desktop` wireframe van Jeroen.

**Comment by MichelleDautzenberg** [comment]
Dubbel met #275
