### ISSUE TITLE
Als casusregisseur wil ik dat andere organisatieonderdelen kunnen zien dat een evenement op een locatie gaat plaatsvinden

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#289]
zodat zij geen dingen gaan plannen die in conflict zijn met mijn evenement.

Kijken hoe dit eenvoudig demobaar kan worden gemaakt.

**Comment by sergei-maertens** [comment]
Hangt nauw samen met #289 - in principe hetzelfde idee.
