### ISSUE TITLE
Als ketenregisseur wil ik een overzicht kunnen inzien van alle evenementen

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#291]
Rol manager die alles kan inzien.

**Comment by sergei-maertens** [comment]
IPM = Informatie & procesmanager (1 laag boven zaakcoördinator)

**Comment by MichelleDautzenberg** [comment]
IPM aangepast naar ketenregisseur. 
Ketenregisseur heeft overzicht over alle evenementenketens. (één keten onder regie casusregisseur)
