### ISSUE TITLE
Als functioneel beheerder wil ik in het ZTC een resultaattype kunnen toekennen aan het zaaktype Evenementvergunning en het zaaktype Ontheffing drank- en horecavergunning. 

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#292]
Bij deze twee procestypen blijf ik een foutmelding krijgen als ik het bijhorende resultaattype probeer toe te voegen. Het lijkt specifiek fout te gaan bij het procestype https://referentielijsten-api.vng.cloud/api/v1/procestypen/035d5ce8-d4f8-4f23-a386-fe2ea136d9e3 

Daaraan wil ik een resultaat toevoegen met resultaattype: https://referentielijsten-api.vng.cloud/api/v1/resultaattypeomschrijvingen/fb65d251-1518-4185-865f-b8bdcfad07b1

En met resultaat": https://referentielijsten-api.vng.cloud/api/v1/resultaten/cbf810ed-63ac-4454-bd54-0040383428a8

**Comment by MichelleDautzenberg** [comment]
Sinds er iets veranderd is in de referentielijsten, weet ik niet meer waar ik de juiste url van het juiste resultaat kan vinden?

**Comment by sergei-maertens** [comment]
Okay, oorzaak gevonden - `Selectielijst procestype` was leeg in het zaaktype, waardoor de validatie inderdaad faalt in `Resultaattype`. Er is verwarring met het blokje 'referentieproces', waar de referentie wel ingevuld is.

Fixes doorgevoerd:

* Procestypen worden nu in de admin opgehaald uit de API en netjes in een dropdown gepresenteerd, dus copy-pasten en ophalen van URLs manueel hoeft niet meer
* Resultaattype validatie ziet nu als er geen procestype gezet is, en geeft een edit-link naar het zaaktype om dit te fixen.

Fixes pending:

* Dropdown voor mogelijke resultaten, gebaseerd op procestype van selectielijst.

**Comment by sergei-maertens** [comment]
Inrichting is gelukt, verdere improvements landen later
