### ISSUE TITLE
fout 500 bij vastleggen project BING regulier

### ISSUE THREAD

**Issue by JurjenBert** [GemeenteUtrecht/ZGW#293]
# Bug
Via http://bing-old.k8s.dc1.proeftuin.utrecht.nl/medewerkers volgt bij het aanmaken van een project (via dasboard BING, +project aanmelden) consequent een foutmelding.

Het lijkt niet uit te maken welke datum je selecteert, ook bij keuze geen voorkeur volgt server error 500
Het gaat om keuze Regulier. 

 

[voeg label 'Bug' toe]

**Comment by sergei-maertens** [comment]
Oorzaak gevonden, fix wordt uitgerold.

**Comment by sergei-maertens** [comment]
Fix uitgerold - kan geverifieerd worden

**Comment by JurjenBert** [comment]
hij doet het weer!
