### ISSUE TITLE
vastleggen BING project versneld gaat niet goed

### ISSUE THREAD

**Issue by JurjenBert** [GemeenteUtrecht/ZGW#294]
# Bug
Via http://bing-old.k8s.dc1.proeftuin.utrecht.nl/medewerkers gaat het aanmaken van een project (via dasboard BING, +project aanmelden)  niet als verwacht in geval van keuze versneld.  
Er wordt geen project id meegegeven en de terugkoppeling over de API call ziet er niet goed uit. 

![opslaan](https://user-images.githubusercontent.com/40294293/64598338-d9ea5600-d3b7-11e9-9f87-402f020783ff.PNG)

**Comment by sergei-maertens** [comment]
Bedankt voor het melden. Ik moest de BInG nog iets verder terugrollen, wordt nu uitgerold.

**Comment by sergei-maertens** [comment]
Fix uitgerold - kan geverifieerd worden

**Comment by JurjenBert** [comment]
hij doet het weer!
