### ISSUE TITLE
Als GU medewerker wil ik Camunda als BPMN engine geïnstalleerd hebben

### ISSUE THREAD

**Issue by CMasselink** [GemeenteUtrecht/ZGW#3]
zodat we processen van andere gemeenten, zoals het parkeervergunningen proces van Haarlem, kunnen importeren en hergebruiken.

**Bepaling prioriteit door PO**

- [ ] TODO

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] TODO

**Acceptatiecriteria**
- [ ] TODO

**Taken**
- [ ] TODO

**Comment by sergei-maertens** [comment]
In de Gitlab repo (https://gitlab.com/gemeente-utrecht/zgw-kubernetes/) staan Helm charts & templates voor Camunda, echter deze kan ik niet zien binnen de zgw namespace, en ook het domein uitproberen geeft een 404, dus het lijkt erop dat dit nog niet gedeployed is.

Op te volgen door @bartjkdp?
