### ISSUE TITLE
Als burger wil ik digitaal alle benodigde stukken kunnen aanleveren

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#30]
...zodat ik dit niet alsnog met de post of aan de balie hoef te doen. 

* drag & drop, 
* configureren max grootte van uploads + user feedback

Uploaden in DRC

Links naar binaire data moeten ondersteund worden.

**Bepaling prioriteit door PO**

- [ ] TODO

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] TODO

**Acceptatiecriteria**
- [ ] TODO

**Taken**
- [ ] TODO

**Comment by sergei-maertens** [comment]
Drag & drop voegt voor de proeftuin weinig toe, dus dat niet gedaan.

Wel mogelijk nu:

* configureren welke bestanden van toepassing zijn voor toetswijze
* inzien welke bestanden al toegevoegd waren
