### ISSUE TITLE
[AFGEVOERD] Als medewerker wil ik vanuit een zaak een document kunnen toevoegen/bewerken/verwijderen,

### ISSUE THREAD

**Issue by JurjenBert** [GemeenteUtrecht/ZGW#307]
...zodat ik met collega's aan een besluit kan werken in de context van een zaak.

**Comment by CMasselink** [comment]
Een document zou je in principe toch nooit mogen verwijderen als het wel een zaakrelevant document is?

**Comment by JurjenBert** [comment]
De redenering is dat als ik per ongeluk een verkeerd document in mijn zaak heb gehangen, ik er dat ook uit zou willen kunnen halen.

**Comment by CMasselink** [comment]
Vanuit die context snap ik het . Ik zou me kunnen voorstellen dat je het verwijderen van documenten bijvoorbeeld alleen voor record managers mogelijk maakt maar dat is vooral een autorisatie vraagstuk...
