### ISSUE TITLE
Als (record)manager/proceseigenaar wil ik inzage hebben in de configuraties en betrokken componenten bij mijn proces

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#323]
...zodat ik overzicht op het informatiebeheer van mijn proces kan houden. 
En het systematisch overzicht vervangen kan worden. 

De beheermodule moet bevatten:
- Inzage vanuit proces
- Bij mijn proces betrokken componenten en hun (oude, huidige, toekomstige) configuraties
- Links naar de beheermodules van de afzonderlijke componenten
- Versiebeheer
- Nieuwe voorstellen kunnen doen

**Comment by sergei-maertens** [comment]
Kapstok userstory, done, zijn nu meer fine grained user stories
