### ISSUE TITLE
[AFGEVOERD] Als functioneel beheerder wil ik snappen hoe NLX werkt

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#328]
Klopt het dat verkeer niet door de NLX gaat, maar via Inway bij ene partij en Outway bij andere partij? En dus NLX-registry alleen de weg wijst?

Kunnen Inway en Outway wel zoveel verkeer aan?
Wie beheert de Inway en Outway? Wat als ze er uit liggen? 

NLX neemt routering, beveiliging over van de OpenTunnel. Maar NLX doet geen buffering, vertaling, zoals OpenTunnel? 
Wat voor plaats krijgt OpenTunnel binnen de vijf lagen?

**Comment by MichelleDautzenberg** [comment]
Graag ook Joyce, Roland en Frank M. betrekken

**Comment by sergei-maertens** [comment]
@MichelleDautzenberg ik heb het issue doorgezet naar iemand van NLX team!

Al even kort mijn perspectief:

> Klopt het dat verkeer niet door de NLX gaat, maar via Inway bij ene partij en Outway bij andere partij?
> En dus NLX-registry alleen de weg wijst?

Een aanbieder van een service/API heeft inderdaad een inway in hun netwerk draaien. In de configuratie daarvan wordt aangegegeven welke services beschikbaar zijn en waar ze staan ([voorbeeld config](https://docs.nlx.io/try-nlx/provide-an-api/#the-api)).

Iemand die de API consumeert, doet dit door binnen hun netwerk een Outway te starten. Outway en Inway krijgen de directory informatie (en verversen deze regelmatig als ik het goed heb). De inway kondigt zichzelf aan bij de directory, en op die manier kunnen outway en inway verbinding maken. Dat doen ze naar mijn begrip inderdaad niet via een tussenpersoon, maar direct met elkaar. De directory is dan inderdaad een 'wegwijzer'.

> Kunnen Inway en Outway wel zoveel verkeer aan?

Daar zijn ze bij NLX voor performance testing aan het doen, en vooralsnog ziet dat er heel positief uit. De performance reports zijn ergens op [gitlab](https://gitlab.com/commonground/nlx) te vinden geloof ik.

Daarnaast worden de inway en outway als docker container aangeboden, dus als blijkt dat er veel trafiek is, zou het aantal replicas binnen utrecht van de inway kunnen opgeschaald worden om hiermee om te gaan. Dat is vrij eenvoudig geregeld in een Kubernetes infrastructuur. Voor outways geldt hetzelfde.

> Wie beheert de Inway en Outway? Wat als ze er uit liggen?

Een inway draait in de omgeving van de aanbiedende partij. Dus in onze proeftuin draaien er één of meerdere inways in de Kubernetes cluster. Deze is self-healing, en als het toch helemaal fout gaat, dan moet dit door de devops van GU opgevolgd worden (in de praktijk zal ik waarschijnlijk eerste zijn om dit op te pakken en dan afhankelijk van het probleem wordt de hostingpartij of NLX-team zelf gecontacteerd om op te lossen).

Voor de outway gaat weer een gelijk verhaal op.

> NLX neemt routering, beveiliging over van de OpenTunnel. Maar NLX doet geen buffering, vertaling, zoals OpenTunnel?
> Wat voor plaats krijgt OpenTunnel binnen de vijf lagen?

Ik ben niet bekend met OpenTunnel. Maar NLX voorziet inderdaad niet in vertaling of buffering. NLX voorziet connectiviteit tussen organisaties met als doel de doelbinding van gegevensopvraag te kunnen loggen.

**Comment by ehotting** [comment]
Prima perspectief @sergei-maertens :)

Paar aanvullingen:

- NLX is gebouwd voor maximalisatie performance en minimalisatie beheer. Tegelijk lossen we een paar generiek vraagstukken op zoals uniforme logging in kader AVG en correcte verdeling  verantwoordelijkheden tussen organisatie mbt authenticatie en autorisatie. We draaien inderdaad benchmarks  op allerlei systemen. Een Raspberry Pi is al snel genoeg om alle traffic van een grote gemeente af te handelen. Weinig mensen zullen dat ook werkelijk doen, een gangbare server met 8 GB RAM, "average" latency en packet size verstouwt nu zo'n 6000 requests per seconde, inclusief technische en functionele logging op hot path (oftewel, wanneer logging faalt gaat request niet door).

- Inways en Outways zijn qua "online zijn"  verantwoordelijkheid van de aanbiedende en vragende organisatie. Wanneer de NLX directory onverhoopt offline is dan draait het verkeer tussen organisatie gewoon door, maar kunnen geen nieuwe API's in het  netwerk worden geïntroduceerd. Overigens hosten we  de NLX Directory wel met zeer hoge uptime, in de toekomst High Available.

- In de Common Ground visie vindt geen translatie en orkestratie plaats. Er is geen ESB nodig, want data wordt  gebrruikt  zoals de API deze aanbiedt - wanneer  data toch in andere vorm nodig is dient de aanbieder daar een andere resource of endpoint voor aan te bieden, of moet de vragende partij een API bouwen die e.e.a. omzet. Wel zullen ESB's blijven bestaan om de link tussen oude en nieuwe wereld te vormen.

- Security:  NLX kan evt voor of achter security componenten zoals IDS, IPS, WAF etc geplaatst worden. Wat ons betreft is dat niet nodig, maar als een geemente daar redenen toe ziet is het mogelijk. Dat soort use cases bespreken we overigens graag, zodat we e.e.a beter passend kunnen maken of wellicht best  practises kunnen documenteren.

Overigens zeer welkom om eens langs te komen, we zitten op Hoog Catharijne.

**Comment by spreeker** [comment]
Klopt het dat verkeer niet door de NLX gaat, maar via Inway bij ene partij en Outway bij andere partij? En dus NLX-registry alleen de weg wijst?

- Ja, nlx is een soort telefoonboek van bekende en geauthenticeerde deelnemers.

Kunnen Inway en Outway wel zoveel verkeer aan?

 - Ja, met heel veel gemak.

Wie beheert de Inway en Outway? Wat als ze er uit liggen?

- De organisatie. Ze zijn echter minimaal in complexiteit en onderhoud.
- De data officer heeft ook een mooie interface om de verbindingen die er zijn tussen organisaties
  te beheren.

NLX neemt routering, beveiliging over van de OpenTunnel. Maar NLX doet geen buffering, vertaling, zoals OpenTunnel?
Wat voor plaats krijgt OpenTunnel binnen de vijf lagen?

Als ik als engineer naar opentunnel zoek en bekijk, zie ik helemaal geen open software of open oplossing. Dat verbaasd mij dan ik kan niet beoordelen wat voor software daar achter zit. Dan heb ik al snel mijn bedenkingen. NLX daarintegen is helemaal open en opensource. NLX doet geen vertalingen want de data gaat niet door een centraal punt en wij kunnen de data ook niet inzien en wij weten ook niet wie met wie praat en wat er dan over de lijn gaat. Dat weten alleen de beheerders / organisaties van een INWAY en OUTWAY.
NLX zorgt voor gestandaardiseerde geauthtenticeerde toegang die voldoet aan de AVG.

**Comment by frankmijn** [comment]
Nog een checkvraag: logging van verzoeken vindt toch plaats op de inway en outway? Of is er toch een centrale logging?

**Comment by spreeker** [comment]
Er is geen centrale logging. De organisatie s zijn zelf verantwoordelijk voor de logging op inways en outways.

**Comment by ehotting** [comment]
<img width="1304" alt="Screenshot 2019-11-27 at 19 00 13" src="https://user-images.githubusercontent.com/20684884/69748244-31db6200-1148-11ea-9902-30cb18580448.png">
NLX bestaat uit de blauwe componenten. Er wordt wel default een PostgreSQL database meegeinstalleerd maar best practise is om per organisatie centrale logging te regelen waar de inways en outways naar wegschrijven. 

Centrale logging binnen een organisatie is dus aan te bevelen.
Centrale logging in de zin van centraal voor heel NL gebeurt niet, dat kan ook niet omdat alle datacommunicatie peer-2-peer tussen organisaties plaatsvindt zonder tussenkomst van een centrale organisatie, knooppunt oid. De enigen die de requests kunnen zien zijn de vragende en leverende organisatie.
