### ISSUE TITLE
Als productowner wil ik een PKI overheidscertificaat installeren voor de NLX

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#349]
Hierbij de documentatie voor het aanvragen van een PKI-Overheid certificaat: https://docs.nlx.io/use-nlx/request-a-production-cert

**Comment by MichelleDautzenberg** [comment]
Aanvraag loopt, maar kost wat tijd.

**Comment by sergei-maertens** [comment]
Certificaat is ontvangen, nu hebben we enkel van auto nog de private key nodig om het effectief te kunnen installeren.

**Comment by sergei-maertens** [comment]
Blijkt dat we G3 certificaat gekregen hebben in plaats van G1, dus terug naar af...

**Comment by sergei-maertens** [comment]
Certificaat is geïnstalleerd en de inway en outway draaien. Er is nu nog 1 afhankelijkheid met Cyso om een IP-adres te krijgen voor de load-balancer.

**Comment by sergei-maertens** [comment]
DNS is nu ook ingesteld!
