### ISSUE TITLE
als functioneel beheerder wil ik weten hoe we zaken kunnen koppelen aan één of meerdere objecten of onderwerpen, 

### ISSUE THREAD

**Issue by JurjenBert** [GemeenteUtrecht/ZGW#355]
zodat we er in de toekomst voor kunnen zorgen dat medewerkers zaken en zaakgerichte registrtaties kunnen koppelen aan objecten en onderwerpen. 
Dit zou er uiteindelijk toe moeten leiden dat medewerkers alle zaken terug kunnen vinden die betrekking hebben op hetzelfde object of onderwerp. 

Onder objecten/onderwerpen wordt hier verstaan: 
1) gegevens die voorkomen in basisregistraties (BRP, BAG, BKR, NHR etc) en kernregistraties (zoals kernregistratie van medewerkers). 
2) thema's, onderwerpen en dergelijke.  

We hebben het idee dat bovenstaande kan met behulp van eigenschappen en informatiobjecten binnen een zaaktype, maar weten niet hoe dat zou moeten met placebo zaken.

**Comment by MichelleDautzenberg** [comment]
Dubbel met de EPIC, daarom gesloten.
