### ISSUE TITLE
Als functioneel beheerder wil ik herbruikbare componenten voor de bevraging van Haal Centraal API's,

### ISSUE THREAD

**Issue by JurjenBert** [GemeenteUtrecht/ZGW#356]
...zodat ik bij de inrichting van een keten deze bevraging niet hoef te ontwikkelen. 
De bronnen moeten worden afgenomen via de NLX laag. 
Het gaat in eerste instantie om:
1. Basisregistratie Adressen en Gebouwen (BAG)
2. Basisregistratie Topografie en Basisregistratie Grootschalige Topografie (BRT/BGT)
3. Landelijke Voorziening Waardering Onroerende Zaken (WOZ)
4. Basisregistratie Personen (BRP)

Ik wil de werking van van de bevraging kunnen demonstreren door vanuit een scherm de APIs de benaderen en de resultaten terug te zien op mijn scherm. Wellicht zou een eerste vraag kunnen leiden tot meerdere vervolgvragen en antwoorden. Bijvoorbeeld: zoek een bedrijf via de NHR en stel een vervolg vraag aan de BAG, BRT/BGT en WOZ over het adres  

**autorisatie**
Aandachtspunt hierbij is hoe bij de ontsluiting van bronnen in de toekomst op systeemniveau (of applicatieniveau) zal worden geautoriseerd (ja/nee mechanisme?). 
Een ander aandachtsptunt is gebruikersautorisatie voor de BRP: onderdeel van bevraging is (?) doelbinding. De doelbinding bepaalt binnen de autorisatie van de gemeente welk deel van de gegevens waarvoor de gemeente is geautoriseerd is, mag worden teruggeven als antwoord op deze specifieke vraag.  

Bij toekomstig gebruik van dit component binnen een keten wordt uitgewerkt wat er met de informatie uit het antwoordbericht gebeurt.  Hier komt ook  gebruikers en systeemautorisatie weer
aan de orde.

**Comment by MichelleDautzenberg** [comment]
We gaan al deze APIs los implementeren, omdat de status erg verschilt. WE maken dus ook losse userstories per API. Daarmee sluiten we deze userstory.
