### ISSUE TITLE
Als medewerker wil ik een zaak van het zaaktype 'Pand beheren' kunnen koppelen aan een object in de BAG 

### ISSUE THREAD

**Issue by JurjenBert** [GemeenteUtrecht/ZGW#362]
(Basisregistratie adressen en gebouwen), zodat bij de behandeling van de zaak duidelijk is op welk object de aanvraag betrekking heeft. 
In de zaak die uiteindelijk wordt aangemaakt moet een verwijzing naar het BAG object worden opgenomen. 
Bij de behandeling van de aanvraag door een medewerker, moet de medewerker kunnen zien aan welk object de aanvraag is gekoppeld.
De BAG gegevens moeten worden opgehaald via de haal centraal API’s. 
https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen 
https://www.vngrealisatie.nl/producten/haal-centraal

**Comment by sergei-maertens** [comment]
@JurjenBert er is de BPTL task voor het relateren van panden en deze zijn zichtbaar in de ZAC - dekt dit hiermee de user story af? Dit loopt nu via Camunda proces.

**Comment by JurjenBert** [comment]
Is prima zo, lijkt me. Het ging hier inderdaad om het relateren. @
