### ISSUE TITLE
Als architect wil ik helderheid over de gevolgen van pollen van tasks in de BPTL

### ISSUE THREAD

**Issue by frankmijn** [GemeenteUtrecht/ZGW#365]
De BPTL pollt nu elke minuut voor tasks die open staan en voert deze dan uit. De vragen die ik heb:

- Wat zijn de gevolgen voor de gebruikerservaring op het moment dat informatie moet worden teruggegeven? 
- Wie is verantwoordelijk voor het afhandelen van foutafhandeling als bijvoorbeeld een zaakregistratiecomponent niet te bereiken is?

**Comment by sergei-maertens** [comment]
> Wat zijn de gevolgen voor de gebruikerservaring op het moment dat informatie moet worden teruggegeven?

Ik neem aan dat je dan doelt op het teruggeven van een zaakidentificatie, bijvoorbeeld?

Op dit moment zit je dan idd met worst-case een minuut wachten (loader/spinner oid) tot dit teruggegeven wordt, tenzij je natuurlijk al een unieke zaakidentificatie zelf meegeeft voor het aanmaken van de zaak.

De BPTL kan ook vaker pollen (elke 5s) bijvoorbeeld, of (en dit heeft mijn voorkeur) we voegen support toe voor long-polling. Dan wordt de taak uitgevoerd zodra die aankomt bij Camunda, en is het allemaal veel snappier.

> Wie is verantwoordelijk voor het afhandelen van foutafhandeling als bijvoorbeeld een zaakregistratiecomponent niet te bereiken is?

In eerste instantie zijn we nu bezig met reporting/dashboards toe te voegen om zicht te krijgen op gefaalde taken. Daar kunnen we ook e-mail-reporting aan toevoegen zodat je de verantwoordelijken in BPTL dan kan instellen. Dat kan iets globaals zijn, of per taak instellen naar wie de e-mail moet gaan.

**Comment by MichelleDautzenberg** [comment]
Huidige oplossing is afdoende. Blijft wel aandachtspunt.
