### ISSUE TITLE
Als medewerker wil ik een zaak kunnen koppelen aan een projectnaam

### ISSUE THREAD

**Issue by JurjenBert** [GemeenteUtrecht/ZGW#370]
zodat ik zaken op een later moment kan terugvinden aan de hand van een projectnaam.
Lees voor projectnaam ook: wijkaanpak en beleidsthema.

**Comment by MichelleDautzenberg** [comment]
Hiervoor moeten we Projectnaam denk ik toevoegen aan Eigenschap in de zaaktypen. Dan kunnen we in Open Forms definieren dat het in deze eigenschap terecht moet komen.
