### ISSUE TITLE
EPIC: Als fysiek domein medewerker wil ik zaken rond een fysiek object vastleggen en kunnen zoeken

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#373]
...zodat ik alle relevante informatie rond een object kan vastleggen en terugvinden.

O.b.v. pand, adres, geolocatie, projectnaam. 

3 varianten: 

- Vanuit de keten wordt relatie met een object gelegd. (subzaak 'Bestek opstellen' haalt object uit hoofdzaak 'Project uitvoeren').
- Achteraf wordt handmatig relatie met een object gelegd (bv. in afhandelcomponent) (Zaaktype 'Pand beheren') 
- Vanuit een formulier (Sloopmelding) wordt relatie met een object gelegd (zaaktype 'Sloopmelding behandelen').

Userstories:
#389 
#362 
#398 
#363 
#370 
#372 
#387 
#388 
#399 
#400

**Comment by MichelleDautzenberg** [comment]
BAG en BRT hebben APIs en deze hebben we met Kadaster al getest tijdens Hackathon.
BRP heeft ook API, maar daar missen we de API key nog voor.

**Comment by MichelleDautzenberg** [comment]
We beginnen met een demo waarin alleen BAG-object aan zaak wordt gekoppeld. Indien mogelijk ook projectnaam. 

BGT/BRT komt dan later.

**Comment by Tim-Hartog** [comment]
Wordt gedekt door userstory 372
