### ISSUE TITLE
Als functioneel beheerder wil ik duidelijkheid over het gebruik van een landelijk ontwikkelde DTC (dossiertypecatalogus)

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#374]
...zodat we weten of hier landelijk een goede oplossing voor bedacht wordt waardoor we de ZTC niet hoeven te misbruiken.

**Comment by Tim-Hartog** [comment]
Achetrhaald op basis van niet0-zaakrehistratie in Contezza en andere wegen om hiermee om te gaan (RMA, etc.)
