### ISSUE TITLE
Als functioneel beheerder wil ik voor het ruimtelijk domein demo 3 zaaktypen inrichten

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#387]
...zodat we deze in de ruimtelijk demo kunnen toepassen.

We maken: ontwikkelen, beheren en afstoten. 

- [x] Project uitvoeren met subzaak Bestek opstellen
- [x] Pand beheren
- [x] Sloopmelding

Hoort bij EPIC: #373

**Comment by MichelleDautzenberg** [comment]
1) Bestek ontwikkelen (vanuit KIC) (Frank)
2) Pand beheren + subzaak Contract beheren (Jurjen)
3) Sloopmelding (met formulier) (Michelle)

**Comment by MichelleDautzenberg** [comment]
Ik mis alleen nog een resultaattype Verleend, maar die kan ik niet toevoegen. Hiervoor een bug bij OpenZaak aangemaakt.

**Comment by MichelleDautzenberg** [comment]
Alle 4 de zaaktypen zijn aangemaakt en gepubliceerd.

**Comment by sergei-maertens** [comment]
Ziet er prima uit wat mij betreft :+1:
