### ISSUE TITLE
Als functioneel beheerder wil ik voor het ruimtelijk domein demo 3 procesmodellen maken 

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#388]
...zodat ik deze kan gebruiken in de ruimtelijk domein demo. 

gebruik makend van Camunda en bptl. 

- [x] Project uitvoeren met subzaak Bestek ontwikkelen (Michelle)
- [x] Pand beheren (Michelle)
- [x] Sloopmelding (met formulier) (Michelle)

Hoort bij EPIC #373

**Comment by MichelleDautzenberg** [comment]
Je vindt ze hier: https://github.com/GemeenteUtrecht/ZGW/tree/master/BPMN

**Comment by MichelleDautzenberg** [comment]
Note: de modellen voor Project uitvoeren en Bestek opstellen zitten nog in één model. Dit is om de samenhang te laten zien. Voor het deployen moeten ze uit elkaar.
Ik wist echter niet hoe te modelleren dat Bestek opstellen voortkomt uit Project uitvoeren en dan zijn resultaat weer teruggeeft aan Project uitvoeren.

**Comment by MichelleDautzenberg** [comment]
RSIN en Zaaktypen bij startevent opgenomen.

**Comment by sergei-maertens** [comment]
@MichelleDautzenberg ik denk dat je een subprocess-referentie kan opgeven in het hoofdproces, en ze zo los van elkaar kan deployen

Misschien vind je iets op https://docs.camunda.org/manual/7.11/reference/bpmn20/subprocesses/ ?

**Comment by MichelleDautzenberg** [comment]
Ik heb nu voor het starten van een bijdragezaak een Call activity gebruikt.

Voor een bericht van buiten (Inwoner wil zijn aanvraag annuleren) heb ik een embedded subproces gebruikt. (nog afwegen of we daar een boundary event van willen maken).

Wat betreft het terugsturen van het resultaat uit de bijdragezaak naar de hoofdzaak, ik denk dat hier een external task voor gemaakt moet worden. Zo te zien kan Camunda daar zelf niet zo veel mee namelijk: https://docs.camunda.org/manual/7.11/reference/bpmn20/events/message-events/

**Comment by sergei-maertens** [comment]
BPTL task voor het relateren van zaken: https://github.com/GemeenteUtrecht/bptl/pull/53

**Comment by MichelleDautzenberg** [comment]
Modellen zijn af en werken, maar het kan zeker mooier :) Denk dat we daar een nieuwe US van moeten maken met de exacte actiepunten.
