### ISSUE TITLE
Als functioneel beheerder wil ik een eformulier 'Sloopmelding' waarin ik een BAG pand kan kiezen en deze kan relateren aan een zaak

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#389]
...zodat ik hiermee kan aantonen dat ik via een formulier de relatie tussen een zaak en object kan leggen en hier uiteindelijk een demo mee kan geven aan het ruimtelijk domein. 

In het eformulier staat:
- Startdatum sloopwerkzaamheden
- Betreffende pand (BAG object)
- Beschrijving van de sloopwerkzaamheden
- Naam en mailadres contactpersoon
- Upload document

Hoort bij EPIC #373

**Comment by MichelleDautzenberg** [comment]
Hiervoor kan het zaaktype Sloopmelding behandelen gebruikt worden. 
Hier is ook een BPMN model voor gemaakt.

**Comment by sergei-maertens** [comment]
@MichelleDautzenberg als je op https://formulieren.utrechtproeftuin.nl/admin/ inlogt met ADFS, dan stel ik de nodige rechten in zodat je het formulier kan voltooien.

**Comment by MichelleDautzenberg** [comment]
@sergei-maertens Als ik inlog met ADFS zegt hij dat ik geen rechten heb?

**Comment by sergei-maertens** [comment]
@MichelleDautzenberg klopt, by default krijg je geen rechten met eerste ADFS login, vandaar de:

> dan stel ik de nodige rechten in zodat je het formulier kan voltooien.

Ik heb rechten ingesteld nu :)

**Comment by MichelleDautzenberg** [comment]
@sergei-maertens Is de vraag nu aan mij om het formulier verder af te maken?
Zo ja, klopt het dat ik geen datatype String kan selecteren? :)

**Comment by sergei-maertens** [comment]
@MichelleDautzenberg klopt, wat betreft afmaken :)

Datatypes moeten visueel nog even beter gemaakt worden, voor String gebruik je `Char` als datatype en laat je `widget` leeg (dan wordt een enkele input gebruikt) of kies je TextArea (dan krijg je een tekstveld)

**Comment by MichelleDautzenberg** [comment]
Gelukt!
En gelijk een formulier gemaakt voor Project uitvoeren.

**Comment by MichelleDautzenberg** [comment]
Nog de documentupload toevoegen aan dit formulier #419

**Comment by MichelleDautzenberg** [comment]
@sergei-maertens Ook graag meer uitleg over: hoe zorg ik dat alle variabelen uit het formulier op de juiste plek in de zaak terecht komen?

**Comment by MichelleDautzenberg** [comment]
@sergei-maertens Deze kan naar done toch?
Documentenupload zit erin en je kan de variabelen mappen naar juiste eigenschap in de zaak.

**Comment by sergei-maertens** [comment]
Yep!
