### ISSUE TITLE
Ik krijg een 500 error als ik een resultaattype 'Verleend' probeer toe te voegen aan het zaaktype 'Sloopmelding behandelen'

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#391]
# Bug

Het is wel gelukt om de resultaattypen Ingetrokken en Afgewezen toe te voegen, maar bij resultaattype Verleend blijf ik errors krijgen zodra ik op opslaan klik.

Ik vermoed dat dit te maken heeft met de afleidingswijze bronddatum. Omdat dit blijkbaar niet Afgehandeld mag zijn, heb ik Eigenschap en Vervaldatum Besluit geprobeerd. Bij beide krijg ik een 500 error. Het is mij onduidelijk wat ik bij Datumkenmerk moet invullen, dus misschien gaat het daarbij fout.

**Comment by sergei-maertens** [comment]
Komt doordat er in de selectielijst geen bewaartermijn staat voor dat resultaat, volgens de error monitoring. Ik maak een issue in Open Zaak aan.

**Comment by sergei-maertens** [comment]
Upstream bug gefixed

**Comment by MichelleDautzenberg** [comment]
Thanks. Nu wel gelukt.
