### ISSUE TITLE
Als product owner wil ik een memo over de archief-compliancy van OpenZaak

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#393]
zodat ik weet dat door OpenZaak te gebruiken by design de archivering volgens alle wettelijke standaarden verloopt.

**Comment by CMasselink** [comment]
Mocht hier uitkomen dat er onvoldoende functionaliteit in OpenZaak zit / niet voldoende meta data vastgelegd kan worden, dan betekent dat vrij zeker dat dit dan ook in de ZGW standaard mist. 
Daarom hoe dan ook interessant om de uitkomst met de VNG te delen.

**Comment by Tim-Hartog** [comment]
Gereed gemaakt door expertteam
