### ISSUE TITLE
Uitbouw ZAC om zaakbehandeling te doen

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/ZGW#394]
- [x] Verbeter styling/layout
- [ ] Voorbereiding 3 flows
    - [x] Simpele inzage + afhandeling
        - [x] Inzage
        - [x] Afhandeling
    - [ ] Inzage + start (sub)zaak met kopie van gerelateerde zaakobjecten
    - [ ] Inzage + toevoegen van gerelateerd zaakobject
- [x] Onderzoek terugkoppeling met proces (relatie procesinstantie, events, triggers, notificaties?)
- [ ] Inzage in 5 vormen
    - [x] Vanuit een pand ID in de BAG
    - [ ] Vanuit een projectnaam
    - [ ] Vanuit een willekeurige geometrie
    - [ ] Vanuit een adres in de BAG
    - [ ] Vanuit een BSN

**Comment by sergei-maertens** [comment]
Momenteel bezig met tonen van gerelateerde zaakobjecten in ZAC

**Comment by MichelleDautzenberg** [comment]
Nog toevoegen aan _inzage in 5 vormen_:
- Vanuit een projectnaam

Qua prio:
Voor de eerste demo zouden we graag het aanmaken van zaken gekoppeld aan BAG object laten zien. En het zoeken van zaken rond een BAG object.
Daarna graag projectnaam oppakken.

BGT/geometrie/BSN kunnen we later oppakken.

**Comment by sergei-maertens** [comment]
:+1: prima, volgende week wil ik dan wel even bespreken wat het concept "projectnaam" inhoudt, want dat is de enige die ik niet heel erg op de horizon heb qua implementatie :)

**Comment by MichelleDautzenberg** [comment]
Prima. Denk zelf aan een Eigenschap waarop je kan gaan filteren en zoeken straks.

**Comment by sergei-maertens** [comment]
Voldoende voor nu, nieuwe changes komen in nieuw ticket.
