### ISSUE TITLE
Kan Catalogi niet verwijderen

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#395]
# Bug
Onderstaande 3 (test)catalogi probeer ik te verwijderen:
![afbeelding](https://user-images.githubusercontent.com/48316239/76941666-b7a03a80-68fc-11ea-83ed-02e2a766a454.png)

De onderste catalogus (x Kan weg) bevat één zaaktype Objectregistratie. Deze heb ik een einddatum gegeven en probeer ik te verwijderen. Dan krijg ik echter een foutmelding. 

![afbeelding](https://user-images.githubusercontent.com/48316239/76941808-f635f500-68fc-11ea-8c2b-e2b4f018ec2e.png)

![afbeelding](https://user-images.githubusercontent.com/48316239/76941774-e9190600-68fc-11ea-8200-6d0f79155ab2.png)

Ook bijvoorbeeld een statustype kan ik niet meer verwijderen:
![afbeelding](https://user-images.githubusercontent.com/48316239/76942114-78beb480-68fd-11ea-9f08-fca0ab1c3d89.png)

NB: Volgens mij zijn er geen zaken aangemaakt met zaaktypen uit deze catalogi.
En mocht dit wel de reden zijn dat ik niets kan verwijderen, dan zou het fijn zijn als ik daar een duidelijkere melding van kreeg.

**Comment by sergei-maertens** [comment]
Feature request bij Open Zaak: https://github.com/open-zaak/open-zaak/issues/517
