### ISSUE TITLE
Als functioneel beheerder wil ik een handleiding schrijven voor het aansluiten van (externe) applicaties op OpenZaak

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#396]
...zodat ik dit snel en eenduidig kan doen bij het aansluiten van nieuwe taakapplicaties op OpenZaak.

**Comment by MichelleDautzenberg** [comment]
@sergei-maertens @frankmijn 
Zouden jullie hier eens naar willen kijken? https://github.com/GemeenteUtrecht/ZGW/blob/master/documentatie/(externe)%20taakapplicatie%20aansluiten%20op%20OpenZaak.docx 

Het is niet heel uitvoerig, maar een eerste aanzetje van waar we aan moeten denken..

**Comment by sergei-maertens** [comment]
@MichelleDautzenberg ziet er goed uit - paar kleine opmerkingen

* Camunda: wil je process definition ID of key delen? Als je via key proces start, dan wordt altijd meest recente versie gestart.
* Zaaktypen aanmaken: zaaktype moet gepubliceerd zijn voor er zaken van aangemaakt kunnen worden
* postman collectie zal ik deze/volgende week ook op github publiceren, lijkt me handig :)

**Comment by MichelleDautzenberg** [comment]
Aangepast, thanks!
