### ISSUE TITLE
Als functioneel beheerder wil ik kunnen beschikken over naamgevingsconventies voor urls in de proeftuinomgeving,

### ISSUE THREAD

**Issue by JurjenBert** [GemeenteUtrecht/ZGW#397]
...zodat de urls leesbaar zijn en een eenheid vormen.  Er moet rekening gehouden worden met verbanden tussen proeftuin en productie. 
Bijvoorbeeld: We zijn er recentelijk tegenaan gelopen dat het pki overheidscertificaat wat we wilde aanvragen zou gelden voor het domein pre-prod,.proeftuinutrecht.nl.  
Het is de bedoeling dat zo'n certificaat ook voor productie wordt gebruikt, maar in die context is de term pre-prod en proeftuinutrecht niet wenselijk.

**Comment by Tim-Hartog** [comment]
Zijn er inmiddels op basis geaccordeerd stuk "Richtlijn domeinnaambeleid"
