### ISSUE TITLE
Als medewerker wil ik in de ZAC een zaak van het zaaktype 'Pand beheren' kunnen aanmaken en afhandelen

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#398]
...zodat ik dit in een demo voor het fysiek domein kan tonen. 

Idem voor het zaaktype Project uitvoeren, Bestek opstellen en SLoopmelding behandelen.

Ook graag de zaak aan een BAG object kunnen koppelen en indien nog tijd over is ook aan een Projectnaam. Zodat je ook deze zaken kunt terugvinden bij zoeken op BAG object of projectnaam. 

Hoort bij EPIC #373

**Comment by MichelleDautzenberg** [comment]
Formulieren zijn te zien in ZAC, maar nog niet in te dienen. Afhandelen in ZAC kan wel. Zaken terugzoeken obv object kan ook, maar nog niet op projectnaam (eigenschap).

**Comment by MichelleDautzenberg** [comment]
Deze hangt nog even op de bptl taak om een vervolgzaak aan te maken.
Pand beheren volgt namelijk op Project uitvoeren.

**Comment by sergei-maertens** [comment]
Is dus afhankelijk van #449

**Comment by MichelleDautzenberg** [comment]
Zie pull request
