### ISSUE TITLE
AFGEVOERD: Als huwelijksplanner teamlid wil ik de huwelijksplanner API's op onze eigen infrastructuur hebben draaien

### ISSUE THREAD

**Issue by CMasselink** [GemeenteUtrecht/ZGW#4]
zodat we intern eenvoudig gebruik kunnen maken van deze API's. 

**Bepaling prioriteit door PO**

- [ ] TODO

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] TODO

**Acceptatiecriteria**
- [ ] TODO

**Taken**
- [ ] TODO

**Comment by Tim-Hartog** [comment]
Was altijd al buiten Scrum belegd: geen betrokkenheid van scrumteam bij realiseren hiervan, geen hoge prioriteit en geen afhankelijkheid naar andere proeftuinactiviteiten. Zodoende afgevoerd.
