### ISSUE TITLE
Als functioneel beheerder wil ik een topic in BPTL voor het relateren van BRT/BGT-object aan een zaak

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#400]
...zodat ik dit in een demo aan het fysiek domein kan laten zien. 

Hoort bij EPIC #373  en bij US #363

**Comment by MichelleDautzenberg** [comment]
beter om dit generiek op te pakken. Zie #435

**Comment by sergei-maertens** [comment]
Er is een generieke BPTL taak voor het relateren van ZaakObjecten
