### ISSUE TITLE
als developer wil ik webhook/callback functionaliteit in de BPTL

### ISSUE THREAD

**Issue by CMasselink** [GemeenteUtrecht/ZGW#410]
zodat de applicatie die de taak gestart heeft, genotificeerd wordt als de taak voltooid is en verder kan met het proces.

Op dit moment moet de taakapplicatie die een taak heeft gestart, pollen om te weten of een taak succesvol is afgerond en voordat er gebruik gemaakt kan worden van de variabelen die in het proces gevuld worden.
Het is handiger als de applicatie op de hoogte gesteld wordt als de taak is uitgevoerd zodat de applicatie dan de gegevens op kan halen ipv constant pollen.

**Comment by sergei-maertens** [comment]
Done :-) Camunda tasks kunnen nu een `callbackUrl` process variable uitlezen en daar een POST naartoe sturen.
