### ISSUE TITLE
Documentatie Vernietigingsoplossing en procesverloop (Maykin-variant) door FB

### ISSUE THREAD

**Issue by shazada** [GemeenteUtrecht/ZGW#413]
Er is op dit moment documentatie opgeleverd.
Deze taak om het vernietigingsproces te accepteren op basis van de documentatie.

**Comment by sergei-maertens** [comment]
Docs staan hier: https://github.com/GemeenteUtrecht/record-management-app/tree/master/doc

En worden gepubliceerd op https://record-management-app.readthedocs.io/en/latest/
