### ISSUE TITLE
Als functioneel beheerder wil ik een overzicht van zaken die altijd door onszelf configurabel moeten zijn

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#417]
...zodat we een leidraad hebben voor leveranciers en wij in control blijven over de gemaakte applicaties.

**Comment by MichelleDautzenberg** [comment]
Altijd configurabel door FB:
- Procesmodellen (Camunda of Activiti)
- Autorisaties op rolniveau en gebruikersniveau
- Informatieve teksten/afbeeldingen in de app
- (Templates voor) berichten, notificaties, reminders, bevestigingsmails
- Koppelingen (verwijzing naar gerelateerde service)
- Huisstijl CSS

**Comment by MichelleDautzenberg** [comment]
Aanvullingen hierop @JurjenBert en @FrankHarbers ?

**Comment by FrankHarbers** [comment]
Zijn de onderdelen die we bij #414 hebben staan niet ook de onderwerpen waar we mee wat moeten kunnen? Misschien de 1 meer dan de ander maar wel overal wat mee kunnen.

**Comment by MichelleDautzenberg** [comment]
Ja klopt inderdaad wel. Probeer het hier alleen wat generieker op te schrijven zodat we er een soort van handout aan een nieuwe leverancier kunnen meegeven straks.
