### ISSUE TITLE
Als eindgebruiker wil ik meteen nieuwe zaken zien in de ZAC

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/ZGW#432]
Wanneer een zaak aangemaakt wordt door een ander systeem, dan moet deze meteen zichtbaar zijn bij een refresh van de ZAC.

Dit betekent dat er cache-invalidatie moet plaatsvinden als reactie op een notificatie van zaak-creatie.

**Comment by MichelleDautzenberg** [comment]
Getest met Ritense formulier en Open Forms en zie direct de zaak verschijnen in de ZAC.
