### ISSUE TITLE
Als gebruiker wil ik in de ZAC in het overzicht van adressen die bij een BAG object horen naast huisnummer, ook huisnummertoevoeging en huisnummerletter zien,

### ISSUE THREAD

**Issue by JurjenBert** [GemeenteUtrecht/ZGW#433]
...zodat ik onderscheid kan maken tussen adressen die gelijk zijn in de combinatie straatnaam en huisnummer, maar afwijkende huisnummerletters hebben.

Voorbeeld: zoek naar Keizersgracht 117 in de ZAC en er wordt het BAG object getoond met 5 keer hetzelfde adres: Keizersgracht 117. Het zijn eigenlijk 5 verschillende adressen: Keizersgracht 117 A t/m 117 E.

**Comment by sergei-maertens** [comment]
Vorige sprint toegevoegd.
