### ISSUE TITLE
Figure out and fix why Camunda errors with db transaction errors on task completion

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/ZGW#437]
Case in point: https://bptl.utrechtproeftuin.nl/tasks/909/

Happened a couple times now, especially when there's a high degree of concurrency. An External Task is being marked as complete in Camunda after it is done, and Camunda itself seems stuck in a database transaction, yielding a 500 error.

This leads to the task not being unlocked and the process instance being stalled until the lock expires (currently 10 minutes).

**Comment by sergei-maertens** [comment]
"Fix" is in https://github.com/GemeenteUtrecht/bptl/commit/edca3c504b3c6c071cb1726f8711611bf0caef9b

**Comment by MichelleDautzenberg** [comment]
Geen fouten meer gezien sinds de fix!
