### ISSUE TITLE
[ZAC] Create a Rol for a Zaak when a staff user claims a user task

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/ZGW#441]
Given a zaak created as part of a BPMN process instance...
With a user task requiring user input in the ZAC...
Then
When the user clicks the "claim" button for that task in the ZAC...

the ZAC should create a Rol object for the given zaak (https://zaken-api.vng.cloud/api/v1/schema/#operation/rol_create) with:

- `betrokkeneType=medewerker` 
- `betrokkeneIdentificatie` set to properties from `request.user`

Note that Conduction has a component for Medewerker registration, but there are [open questions](https://github.com/VNG-Realisatie/huwelijksplanner/issues/591)

**Comment by annashamray** [comment]
developed in https://github.com/GemeenteUtrecht/zaakafhandelcomponent/pull/24
