### ISSUE TITLE
Support verblijfsobjecten as ZaakObject

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/ZGW#447]
Currently, in Open Forms there's the ability to select a `Pand` from the [BAG API](https://bag.basisregistraties.overheid.nl/restful-api/-/article/basisregistraties-adressen-en-gebouwen-bag-). The adres autocomplete suggests these locations. A Pand has a geographic definition.

However, this is a bit limited, as we also want to connect more fine-grained [objects](https://openzaak.utrechtproeftuin.nl/zaken/api/v1/schema/#operation/zaakobject_create), notably:

* verblijfsobject
* nummeraanduiding
* woonplaats

Focus on `verblijfsobject` first for this ticket. I noticed that the `objectType` `verblijfsobject` is not part of the standard, I think that's because we used an older version of RGBZ.

To achieve this, the following tasks are required:

- [x] Support verblijfsobjecten in map search ([location server docs](https://github.com/PDOK/locatieserver/wiki/API-Locatieserver))
    - [ ] ~~Add type options to the map search: `pand` and/or `verblijfsobjecten`. Frontend selections should have an effect on the location server calls made (and influence the autocomplete results)~~
    - [x] Display the verblijfsobject on the map after search result selection
    - [x] Pass the BAG API URL-reference in the submitted form
- [x] In the ZAC, display the relevant zaakobjecten
    - [x] Ensure that ZaakObject of type `verblijfsobject` can correctly be displayed
    - [x] Ensure that pand can still be displayed
- [x] In the ZAC, extend the search options to also search on verblijfsobject. you can re-use the Open Forms code.

**Comment by MichelleDautzenberg** [comment]
Ook nog te onderzoeken: binnen een BAG-object kan ook nog sprake zijn van een geolocatie (voor woonboten) en standplaatsen (voor woonwagens).

**Comment by sergei-maertens** [comment]
@MichelleDautzenberg best maak je losse issues aan hiervoor: ligplaatsen en standplaatsen. Die zag ik inderdaad al in de API spec staan :-)
