### ISSUE TITLE
[ZAC] Add permission checks to file downloads

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/ZGW#450]
- [ ] Check download permission based on zaak access
- [ ] Check download permission based on vertrouwelijkheidaanduiding
- [ ] Optionally define a different permission for documents?

Split off from #445

**Comment by CMasselink** [comment]
Meer een vraag die door een DISO beantwoord moet worden maar: mag iemand die **niet** geautoriseerd is op documenten met een vertoruwelijkheidsniveau geheim, uberhaupt mogen zien dat er een document met geheim aan de zaak is toegevoegd? Mag bijvoorbeeld de titel van een document zichtbaar zijn? Oftewel: moet je alleen het downloaden blokkeren of meer?

**Comment by sergei-maertens** [comment]
Goeie vraag - dit kan in principe ook prima in twee permissions uitgesplitst worden: downloaden en/of zien

**Comment by sergei-maertens** [comment]
@CMasselink FYI, in https://github.com/GemeenteUtrecht/zaakafhandelcomponent/pull/84 tonen we ook niet de documenten waar je geen toegang voor hebt. Staat uiteraard niet in beton gegoten, maar met die PR kan ik wel dit issue sluiten :)
