### ISSUE TITLE
Deelproces adviseren/paraferen

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/ZGW#451]
Qua procesmodellering op grote lijnen:
1. Start hoofdproces, creatie zaak met zaakdocumenten (pak 'em beet 3 documenten) - kan via Open Forms
2. Call Activity subproces - geeft zaakUrl uit het hoofdproces mee als variabele (hoofdZaakUrl in het subproces)
3. subproces start: creatie bijdragezaak "adviseren"
4. subproces user task (of slimme manier met BPTL): selecteer subset aan documenten. Documenten worden opgehaald en afgebeeld op basis van hoofdZaakUrl. Denk dat een formulier zonder velden maar met formKey gelijk aan documentenSelectie prima mechanisme is hiervoor, dat kan de ZAC vervolgens begrijpen. Resultaat is dat er een procesvariabele documenten gezet wordt
5. subprocess BPTL task (multi-instance parallel) die voor elk document in documenten het document koppelt aan de bijdragezaak
6. subprocess user task (multi-instance parallel) voor alle adviseurs. Geef het een form key adviseren en dan kan ik daar in de ZAC weer wat mee
7. subprocess resultaat -> "adviezen gegeven"
8. hoofdproces gaat verder

de adviezen bewaar ik in de ZAC database, en die kan ik vervolgens in de zaak-detail bij de documenten tonen (kolom met # adviezen) en doorklikopties op elk document om alle adviezen te lezen van gebruikers bij een document

data model advies is dan:
- URL naar document in DRC
- gebruiker die advies gaf
- tekstveld met advies

Parafering zal heel vergelijkbaar zijn dan

dit beperkt development ook tot de ZAC, en later kunnen we adviezen/parafen in een eigen API stoppen

**Comment by MichelleDautzenberg** [comment]
Ik verplaats deze naar done en maak een nieuwe userstory aan om het adviesproces ad hoc op te starten.
