### ISSUE TITLE
DATA_UPLOAD_MAX_MEMORY_SIZE for DRC is too low

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/ZGW#453]
# Bug

`DATA_UPLOAD_MAX_MEMORY_SIZE` is 2.5MB by default, which applies to POST/PUT/PATCH bodies. With DRC performing uploads in b64 encoded, it's expected that we will receive files larger than this.

An easy fix is to set `DATA_UPLOAD_MAX_MEMORY_SIZE` to `1Gb` for the foreseeable time, in https://github.com/GemeenteUtrecht/gemma-documentregistratiecomponent/tree/feature/rc-upgrade

**Comment by Tim-Hartog** [comment]
Oud component, nieuwe DRC in de maak
