### ISSUE TITLE
Afleidingswijze brondatum aanpassen voor deelzaken Adviseren en Accorderen

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#486]
...zodat deze de archieftermijn van de hoofdzaak overnemen.

Je zou in OpenZaak moeten kunnen kiezen voor Afleidingswijze 'Gerelateerde zaak' of 'Hoofdzaak'. Dit zouden we eens moeten testen. 

Maar laten we eerste even met KKCD overleggen hoe we met archieftermijnen van deelzaken en bijdragezaken omgaan. Eerder in het programma is er ook eens een uitspraak gedaan dat we niet met deelzaken zouden werken?

**Comment by sergei-maertens** [comment]
@MichelleDautzenberg kan gesloten worden nu we afstappen van deelzaken hiervoor, toch?
