### ISSUE TITLE
Als proceseigenaar wil ik dat het formulier/applicatie zijn taalgebruik en opties aanpast n.a.v. de keuzes van de burger

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#49]
...zodat het formulier duidelijk en simpel is voor de klant. 

Concreet betekent dit dat de waarde van keuzeselecties gebruikt moet worden in plaats van generieke `keuze1/keuze2` teksten.

Er wordt gekozen naar gelang van de keuze Reguliere of Verkorte Procedure een andere documentenset vereist te stellen om de aanvraag te kunnen indienen (meer documenten bij de Reguliere dan de Verkorte Procedure)

**Bepaling prioriteit door PO**

- [ ] TODO

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] TODO

**Acceptatiecriteria**
- [ ] TODO

**Taken**
- [ ] TODO

**Comment by sergei-maertens** [comment]
Voorbeeld: verkorte procedure vs. normale procedure

=> heeft invloed op welke set van documenten relevant is.
