### ISSUE TITLE
Als ZAC gebruiker wil ik dat het overzicht van selecteerbare zaaktypen inklapbaar is,

### ISSUE THREAD

**Issue by JurjenBert** [GemeenteUtrecht/ZGW#492]
...zodat ik zaken zie als ik alle zaken kies. Nu zie je igv van autorisatie voor meer dan circa 20 ZT eerst alle ZT met al dan niet aangevinkte checkboxes. Vaak zul je direct naar het overzicht van zaken willen en geen selectie willen maken van zaken. In dat geval staat het overzicht met de checkboxes in de weg.

**Comment by sergei-maertens** [comment]
pull request met verbeterde UI/UX in https://github.com/GemeenteUtrecht/zaakafhandelcomponent/pull/49
