### ISSUE TITLE
Kan geen afleidingswijze Afgehandeld zetten bij te bewaren zaaktype

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#503]
# Bug

Bij het toevoegen van het zaaktype 'Collegevergadering', probeer ik een resultaattype toe te voegen met als afleidingswijze brondatum 'Afgehandeld.' Aangezien het zaaktype van de categorie Blijvend-bewaren is en geen procestermijn heeft (19.1.6) zou dit gewoon moeten kunnen. 

Volgens dit issue zou deze bug inmiddels opgelost moeten zijn, maar dit lijkt dus nog niet het geval?
https://github.com/VNG-Realisatie/gemma-zaken/issues/1610 

![afbeelding](https://user-images.githubusercontent.com/48316239/88193106-90a49d00-cc3d-11ea-85f8-8e5806820974.png)

**Comment by sergei-maertens** [comment]
Open Zaak PR made: https://github.com/open-zaak/open-zaak/pull/653

**Comment by sergei-maertens** [comment]
@MichelleDautzenberg Open Zaak 1.3.0 staat nu op de proeftuin, je kan verder!

**Comment by MichelleDautzenberg** [comment]
Opgelost
