### ISSUE TITLE
Nieuwe zaken worden niet automatisch getoond in de ZAC

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#504]
# Bug

Nieuwe zaken worden bij FB niet automatisch getoond in de ZAC, ook niet naar refreshen.
Er is een Cache flush voor nodig om nieuwe zaken te tonen.

**Comment by sergei-maertens** [comment]
Oorzaak gevonden, fix gevalideerd en gedeployed.
