### ISSUE TITLE
Superdemo inrichten voor BBV

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#506]
- [x] Zaaktype Bestuurlijke besluitvorming

- [x] Zaaktype Collegevergadering

- [x] Zaaktype Raadsvergadering

- [x] Zaaktype Beleid opstellen

- [x] Informatieobjecttypen: raadsvoorstel, bijlage bij raadsvoorstel, collegevoorstel, bijlage bij collegevoorstel, mandaat, besluit, besluitenlijst, notulen

- [x] Besluittypen: raadsbesluit, collegebesluit

- [x] Formulier Beleid opstellen

- [x] BPMN Beleid opstellen: adviseren en accorderen

- [x] BPMN Bestuurlijke besluitvorming

**Comment by MichelleDautzenberg** [comment]
Hangt op bug #503

**Comment by sergei-maertens** [comment]
https://github.com/open-zaak/open-zaak/issues/656 Open Zaak 1.3.0 bevat bugfix en zal normaal vandaag gereleased worden
