### ISSUE TITLE
Als functioneel beheerder wil ik een ZAC formulier waarin de medewerker kan aangeven welke documenten meegenomen moeten worden naar de bijdragezaak of vervolgzaak

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#517]
...zodat niet automatisch door Camunda alle documenten meegenomen worden. 

Ik wil hierbij ook een ander documenttype kunnen aangeven bij een document (en dan kunnen kiezen uit de mogelijke informatieobjecttypen)

Bv: een "plattegrond" uit mijn hoofdzaak wil ik als 'bijlage bij raadsvoorstel' meenemen naar mijn bijdragezaak.

**Comment by sergei-maertens** [comment]
In eerste instantie focussen we op de deelselectie, het documenttype aanpassen is een complexer verhaal (en wijzigen kan niet in de API, dus je zou sowieso een kopie moeten maken).

**Comment by sergei-maertens** [comment]
Dit is grotendeels gerealiseerd, er was al aardig wat bestaande functionaliteit:

- de formulierimplementatie om documenten te selecteren bestond al. Je gebruikt dit door in Camunda de form key `zac:documentSelectie` op te geven.
- Het procesmodel van "project uitvoeren" is aangepast om dit mee te nemen. Deze start namelijk een bijdragezaak. Zie hiervoor PR #529. Hierin is dus ook de betreffende form key opgenomen.
- De styling van documentselectie in de ZAC is aantrekkelijker gemaakt, met document info/preview die er consistent uitziet met ad-hoc activiteiten
- Functionaliteit is getest en ziet er werkend uit.
