### ISSUE TITLE
Als functioneel beheerder wil ik een generieke bptl taak voor het zetten van een rol

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#518]
...zodat ik een initiator, behandelaar, adviseur en belanghebbende kan zetten bij de zaak.

**Comment by sergei-maertens** [comment]
Is geïmplementeerd en gedeployed, zie topic `zaak-rol` op https://bptl.utrechtproeftuin.nl/taskmappings/ voor de documentatie.

Merk op dat je dus bijvoorbeeld als `betrokkene` de volgende structuur gebruikt:

```json
{
    "betrokkeneType": "medewerker",
    "betrokkeneIdentificatie": {
        "identificatie": "dautz001",
        "voorletters": "M."
    }
}
```

Voor natuurlijk personen kan je ook de HaalCentraal URL gebruiken:

```json
{
    "betrokkeneType": "natuurlijk_persoon",
    "betrokkene": "https://www.haalcentraal.nl/haalcentraal/api/brp/ingeschrevenpersonen/999991723"
}
```

En als `omschrijviging` de omschrijving van het roltype (zoals die dus in Open Zaak in het roltype staat).

**Comment by MichelleDautzenberg** [comment]
Getest en ingebouwd vanuit OpenForms en op vaste plek in Advies-proces.
