### ISSUE TITLE
Als functioneel beheerder wil ik in formulier van OpenForms een dropdown-keuzelijst kunnen opnemen

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#519]
...zodat ik een lijst met opties aan de invuller kan aanbieden.

**Comment by sergei-maertens** [comment]
Dat kan via https://formulieren.utrechtproeftuin.nl/admin/formbuilder/fieldchoice/

Uiteraard is de interface hiervoor... dramatisch.

**Comment by MichelleDautzenberg** [comment]
Gelukt, bedankt!
