### ISSUE TITLE
Als proceseigenaar wil ik dat er niet meer persoonsgegevens wordt uitgevraagd, getoond en opgeslagen dan benodigd

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#52]
...zodat ik voldoe aan de AVG..

Lees: enkel de minimale gegevens om personen te contacteren mogen bewaard worden.

**Bepaling prioriteit door PO**

- [ ] TODO

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] TODO

**Acceptatiecriteria**
- [ ] TODO

**Taken**
- [ ] TODO

**Comment by sergei-maertens** [comment]
De release candidate van ZRC bevat een manier om matchinggegevens van betrokkenen op te slaan. Daar zitten echter niet e-mailadres/telefoon in, en ook de BRP bevat die niet voor zover ik weet. Beste optie is om deze gegevens bij de bing-aanvraag zelf te bewaren, waarschijnlijk.
