### ISSUE TITLE
Als functioneel beheerder wil ik een bptl taak voor het openen van een externe site/applicatie

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#520]
...zodat ik vanuit het procesmodel automatisch een externe website of applicatie kan laten openen.

**Comment by MichelleDautzenberg** [comment]
Is het openen van een externe site een bewuste useractie of dient dit automatisch te gebeuren?

Exacte uitwerking bespreken met gebruikers.

**Comment by JurjenBert** [comment]
voor nu prima.
