### ISSUE TITLE
BPTL-taak 'zaak-eigenschap' geeft error als er geen eigenschappen zijn

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#522]
De BPTL-taak 'zet-eigenschap' geeft een error als er geen eigenschappen zijn. Echter kan dit wel voorkomen.

**Comment by sergei-maertens** [comment]
Fix https://github.com/GemeenteUtrecht/bptl/commit/6bc35222ef1778975c7555dd52136545a8e32c8e is gedeployed - deze zal nu niet meer error/crashen als de eigenschap niet bestaat.
