### ISSUE TITLE
Maak een simpel BPMN model voor de ValidSign integratie

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/ZGW#526]
In eerste instantie doen we een los BPMN model/proces om de BPTL ValidSign integratie te testen/demo-en, daarna kunnen we het opnemen in BBV proces.

**Comment by MichelleDautzenberg** [comment]
Ziet er goed uit, kan je het BPMN model op Github plaatsen zodat ik  hem in een ander proces kan testen?

**Comment by sergei-maertens** [comment]
Die staan in #527 !
