### ISSUE TITLE
Als medewerker wil ik een BBV zaak kunnen starten

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#530]
zodat ik mijn voorstel ter besluitvorming kan aanbieden

De BBV zaak kan los worden opgestart vanuit een formulier of als bijdragezaak vanuit een hoofdzaak.

**Bij invullen BBV formulier voor losse BBV zaak:**

- [x] Metadata zijn in te vullen die later nodig zijn in proces (Xential, Ibabs)
- [x] Documenten zijn te uploaden vanaf netwerkschijf
- [x] Documenten zijn te uploaden vanaf Digiplaza
- [x] Documenten zijn weg te laten

- [ ] Xential sjabloon wordt geopend en ingevulde document wordt opgeslagen bij de zaak (vanuit formulier, ZAC of handmatig?)
- [ ] Word wordt geopend en ingevulde document wordt opgeslagen bij de zaak (vanuit formulier, ZAC of handmatig?)

**Bij invullen BBV formulier vanuit hoofdzaak**

- [x] Reeds bekende metadata (indien er al een hoofdzaak was) worden overgenomen in formulier
- [x] Documenten uit de hoofdzaak kunnen geselecteerd worden om mee te nemen naar BBV bijdragezaak
- [ ] Metadata zijn aan te vullen die later nodig zijn in proces (Xential, Ibabs)
- [x] Documenten zijn te uploaden vanaf netwerkschijf
- [x] Documenten zijn te uploaden vanaf Digiplaza
- [x] Documenten zijn weg te laten

**Na aanmaak BBV zaak:**

- [ ] Zaak kan handmatig gerelateerd worden aan een andere zaak
- [x] Documenten zijn te uploaden vanaf netwerkschijf
- [x] Documenten zijn te uploaden vanaf Digiplaza

- [ ] Xential sjabloon wordt geopend en ingevulde document wordt opgeslagen bij de zaak (vanuit formulier, ZAC of handmatig?)
- [ ] Word wordt geopend en ingevulde document wordt opgeslagen bij de zaak (vanuit formulier, ZAC of handmatig?)

**Comment by JurjenBert** [comment]
demo voor nu akkoord bevonden. Aanvullende user stories worden apart opgenomen.
