### ISSUE TITLE
Als medewerker wil ik in de ZAC bij een zaak extra documenten kunnen uploaden

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#531]
...zodat ik mijn zaak kan aanvullen na het aanmaken ervan

**Comment by sergei-maertens** [comment]
@MichelleDautzenberg is uitgerold op de ZAC - onderaan de tabel heb je nu een knop om docs toe te voegen.

**LET OP** - je ziet deze enkel als je de permissies hiervoor hebt - zorg ervoor dat je dus de permission sets bij de autorisatieprofielen bijwerkt met deze permissie: https://zac.utrechtproeftuin.nl/accounts/auth-profiles/
