### ISSUE TITLE
Als medewerker wil ik een toelichting bij mijn advies/accorderingsvraag kunnen meegeven

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#546]
...zodat de adviseurs/accordeurs weten wat exact mijn vraag is en ik eventuele opmerkingen kan meegeven.

**Comment by MichelleDautzenberg** [comment]
Toelichting wordt in Kownsl vastgelegd.
Deze moet zichtbaar zijn voor de adviseur/accordeur bij het adviseren/accorderen in Kownsl.

**Comment by sergei-maertens** [comment]
Let's keep this in review until it's deployed and tested by FB :)

**Comment by sergei-maertens** [comment]
Gedeployed!
