### ISSUE TITLE
beleid-opstellen form returns 500 error

### ISSUE THREAD

**Issue by annashamray** [GemeenteUtrecht/ZGW#560]
# Bug
Server returns 500 on submission the form: https://formulieren.utrechtproeftuin.nl/forms/beleid-opstellen/ 

The reason is that in custom ZGW field `DocumentUpload` there is a request of `drc-cmis`, which returns 400 error

Sentry details - https://sentry.maykinmedia.nl/maykin-media/open-forms-utrecht-test/issues/269113/?referrer=RegressionActivityEmail

**Comment by MichelleDautzenberg** [comment]
Deze is gefixt.
