### ISSUE TITLE
Als proceseigenaar BInG wil ik dat elk aanvraagdossier met het genomen besluit gearchiveerd wordt

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#63]
Afgevoerd, gebeurd buiten de scope proeftuin. Wij geven enkel de juiste statussen en resultaatcodes mee om dit elders uit te kunnen voeren.

**Comment by sergei-maertens** [comment]
In principe afgedekt door in het ZTC resultaattypen goed in te richten
