### ISSUE TITLE
Als proceseigenaar wil ik dat er personas gecreerd worden waarmee ik een klantreis kan uitvoeren

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#64]
...zodat ik de gebruikerservaring van de ontwikkelde oplossing kan testen. 

persona nodig voor:
- interne aanvrager: Persona Petra als basis gebruiken
- externe aanvrager
- Secretaris: Persona Thea als basis gebruiken. 
- inhoudelijk specialist: Persona Rachid als basis gebruiken. 
- intern commissielid: Persona Hans als basis gebruiken?
- extern commissielid

**Bepaling prioriteit door PO**

- [ ] TODO

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] TODO

**Acceptatiecriteria**
- [ ] TODO

**Taken**
- [ ] TODO

**Comment by JeroenduC** [comment]
Templates staan (nu nog) in Digiplaza.

**Comment by JeroenduC** [comment]
Thea aangepast naar aanleiding van feedback Michelle/Marleen.

**Comment by MichelleDautzenberg** [comment]
Ik sluit deze omdat er nu geen concrete opdracht meer ligt om personas te maken. Mocht dit weer nodig blijken bij implementatie maken we daar nieuwe concrete userstories voor aan.
