### ISSUE TITLE
Als medewerker wil ik zaken kunnen relateren

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#67]
...zodat ik altijd weet wat er rondom deze zaak gebeurd.

**Bepaling prioriteit door PO**

- [ ] TODO

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] TODO

**Acceptatiecriteria**
- [ ] TODO

**Taken**
- [ ] TODO

**Comment by sergei-maertens** [comment]
Kan via `Zaak.relevanteAndereZaken` - afgestemd met VNG en blijkbaar was het e.e.a. veranderd tussen RGBZ versies.

Zit in de API, dus we zijn niet langer geblokkeerd
