### ISSUE TITLE
Zaaktype(s) huwelijk configureren in admin ZTC (na uitleg van Jorik / Sergei over admin.omgeving)

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#70]
...zodat [vul aan].

**Bepaling prioriteit door PO**

- [ ] TODO

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] TODO

**Acceptatiecriteria**
- [ ] TODO

**Taken**
- [ ] TODO

**Comment by JostCrow** [comment]
https://ref.tst.vng.cloud/ztc/admin/

**Comment by CMasselink** [comment]
@JostCrow Dat is de admin module van de bij de VNG gehoste ZTC (dat wist jij uiteraard al, maar ook even voor de rest van het team), de zaaktypes moeten natuurlijk ook lokaal in ons ZTC geconfigureerd worden.
De zaaktypes bij de VNG voor huwelijk zijn nu heel basaal ingericht, ook die kunnen nog wel uitgebreid worden. Het is natuurlijk sowieso handig om te kijken hoe de zaaktypes in de bij de VNG gehoste omgeving er uit zien, om ze daarna over te nemen in de lokale omgeving.

**Comment by sergei-maertens** [comment]
Overnemen van data uit gehoste referentieimplementatie naar lokale omgeving kan via https://ref.tst.vng.cloud/ztc/data/
