### ISSUE TITLE
"Naar binnen halen" van Haarlem-proces 'Afschrift aktes'

### ISSUE THREAD

**Issue by Tim-Hartog** [GemeenteUtrecht/ZGW#73]
# Scrumtaak

[beschrijf de scrumtaak]

[assign aan teamlid]

**Comment by MichelleDautzenberg** [comment]
Als we dit als dockerimage naar binnen halen is het niet te ontleden (want je draait alles of niets) en niet te configureren naar de wens van Utrecht. Daarnaast niet logisch om een aparte dockerimage met Camunda +aktes erin te draaien als we zelf ook Camunda hebben. 
Beter vragen we de procesmodellen en code los op en deployen we dat naar onze eigen Camunda engine.

**Comment by Tim-Hartog** [comment]
**Analyse Michelle Dautzenberg:**
- De dockerimage van Haarlem is eenvoudig op te starten, maar vervolgens weten we niet wat we ermee moeten/kunnen. We missen documentatie over wat het proces precies doet en hoe het werkt (icm de services die eraan vast zitten).
- We zien in het proces dat er extra services worden opgevraagd: webformulieren, een (mock?)BRP, elektronische handtekening app, ZRC, DRC. We kunnen niet goed zien wat er van deze Services in de dockerimage zit, of deze ook voor ons bruikbaar zijn. We hebben hier ook geen documentatie over.  
- Als we het proces handmatig willen starten in Camunda krijgen we een foutmelding. Aan het proces in Camunda te zien is het proces nog niet af en zal het dus ook nog niet werken.
- Aanpassen van de configuraties, database, procesmodellen in de dockerimage van Haarlem is niet mogelijk. Het lijkt daarom zinloos om het op deze manier in Utrecht neer te zetten.
- Beter is om de modellen en code bij Haarlem op te vragen en deze kopie met Utrecht-sausje erover in onze eigen Camunda-installatie te zetten.

**Vervolgafstemming Lazo Bozarov:**
Lazo gaat met Bas de Boer van Haarlem overleggen of proces daar draait en globale analyse wat er aan de hand kan zijn. We zijn er nog niet uit om de sourcecode los op te vragen en zelf op te pakken. Vraag was immers niet of we de code aan de praat zouden kunnen krijgen, maar of dergelijke ontwikkelingen eenvoudig herbruikbaar / uitwisselbaar / over te nemen zijn. Voor nu geen nadere actie totdat expliciet alsnog hiertoe opdracht aan proeftuin wordt gegeven.
