### ISSUE TITLE
Als BInG-aanvrager wil ik grote bestanden en CAD-bestanden kunnen uploaden

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#75]
...zodat ik mijn afbeeldingen en grote bestanden bij de aanvraag kan doen.

* WeTransfer
* Dropbox
* ~~W-schijf~~

=> Asynchroon buiten request-response cycle downloaden

**Bepaling prioriteit door PO**

- [ ] TODO

... eventueel nog toelichting door PO

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] TODO

**Acceptatiecriteria**
- [ ] TODO

**Taken**
- [ ] TODO

**Comment by sergei-maertens** [comment]
DRC spec schrijft nu nog niet voor, maar binnenkort wel: een upload van max 2GB moet kunnen. Er komt ook een mechanisme om grotere bestanden in chunks te uploaden.
