### ISSUE TITLE
Als developer wil ik een DOCKER container met de ZGW services voor het exxellence zaakysteem. 

### ISSUE THREAD

**Issue by JurjenBert** [GemeenteUtrecht/ZGW#80]
...zodat [vul aan].

**Bepaling prioriteit door PO**

- [ ] TODO

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] TODO

**Acceptatiecriteria**
- [ ] TODO

**Taken**
- [ ] TODO

**Comment by CMasselink** [comment]
Ik laat het verder aan de experts over maar wellicht is het handig om per api/service (ZRC, DRC, ZTC, BRC, ORC) een aparte container aan te maken. Zo doen we het in ieder geval met de referentie componenten.
