### ISSUE TITLE
Als BIng-secretaris wil ik in een lopende BInG zaak aan kunnen geven of het een versnelde of standaard procedure betreft.

### ISSUE THREAD

**Issue by JurjenBert** [GemeenteUtrecht/ZGW#82]
...zodat deze definitief vastgelegd kan worden.

De aanvrager kan 'weet het niet' aangeven, of een foute keuze gemaakt hebben. Dit wordt door de secretaris gecontroleerd en eventueel aangepast/vastgelegd.

Dit heeft effect op vervolgkeuzes/procedure:

**Regulier naar versneld:**
Het moet zichtbaar zijn voor de aanvrager dat de toetswijze is aangepast (met notificatie) en dat:
- er geen vergadering meer nodig is --> de reeds geplande vergaderdatum wordt (automatisch) verwijderd 
- de doorlooptijd daarmee verandert --> doorlooptijd is nu korter

**Versneld naar regulier:**
Het moet zichtbaar zijn voor de aanvrager dat de toetswijze is aangepast (met notificatie) en dat:
- er aanvullende documenten nodig zijn --> de aanvrager moet hier een melding van krijgen en de mogelijkheid krijgen om de extra documenten alsnog te uploaden. 
- er wel een vergadering nodig is --> de aanvrager moet hier een melding van krijgen en de mogelijkheid krijgen om alsnog een vergaderdatum te kiezen. 
- de doorlooptijd daarmee verandert --> doorlooptijd is nu langer

**Bepaling prioriteit door PO**

- [ ] TODO

... eventueel nog toelichting door PO

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door PO)
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is voorzien van een analyse (met daarin architectuur, IM, technische beslissingen afgestemd met team)**_
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] TODO

**Acceptatiecriteria**
- [ ] TODO

**Taken**
- [ ] TODO

**Comment by sergei-maertens** [comment]
@MichelleDautzenberg graag de implicaties opsommen :-)

**Comment by sergei-maertens** [comment]
* we doen op dit moment nog niets met doorlooptijd, dus dit achterwege gelaten
* notificeren komt nu niet bij de aanvrager omdat we (nog) geen contactgegevens hebben, er is wel scaffolding in de code om dit goed te laten gaan
